FROM twobombs/deploy-nvidia-docker:minimum

# Install pyqrack en reqs.
RUN apt-get update && apt-get install -y python3-pip
RUN pip3 install pyqrack
RUN pip3 install pyzx
RUN pip3 install cirq
RUN pip3 install mitiq
RUN pip3 install ipyparallel

# benchmarks
RUN git clone https://github.com/vm6502q/pyqrack-jupyter.git

# Install SimulaQron 
RUN pip3 install simulaqron
# RUN simulaqron set backend pyqrack

# Install IBM QC connector
RUN pip3 install -U IBMQuantumExperience

# Install Qiskit
RUN pip3 install qiskit[visualization]
RUN pip3 install qiskit-qrack-provider

# Install qc-client WebUI
RUN apt install -y npm && npm install -g qps-client & apt clean all

EXPOSE 6006 8888
COPY run-minimum-tensor /root/run-minimum-tensor
RUN chmod 744 /root/run-minimum-tensor
ENTRYPOINT /root/run-minimum-tensor
