# mirror nn test script series

export QRACK_SEGMENT_GLOBAL_QB=2
export QRACK_OCL_DEFAULT_DEVICE=0
export QRACK_QTENSORNETWORK_THRESHOLD_QB=0
export QRACK_MAX_PAGING_GB=27
export QRACK_MAX_ALLOC_MB=16000
export QRACK_QPAGER_DEVICES_HOST_POINTER=16.0,1.1
export QRACK_QUNIT_SEPARABILITY_THRESHOLD=0.40

python3 mirror_nn_depth_series.py 56 10 1 True
