FROM twobombs/thereminq-tensors:tensorboards

# hard install tensorflow-quantum
RUN apt update && apt install -y python3-grpcio && apt clean all
RUN pip install --upgrade setuptools && pip cache purge
RUN git clone --depth=1 https://github.com/tensorflow/quantum.git
RUN cd quantum && pip install --ignore-installed -r requirements.txt && pip cache purge

EXPOSE 6080
ENTRYPOINT /root/run-boards
