FROM twobombs/thereminq-tensors
#FROM localai/localai:latest-aio-gpu-nvidia-cuda-12

# python-is-python3
RUN apt update && apt install -y python-is-python3 && apt clean all

# agent will require quantum dependancies

# install runtime requirements
# to speed up the agent process
RUN pip3 install --upgrade pip
RUN pip3 install pyqrack && pip cache purge

# Install Qiskit libaries
RUN pip3 install qiskit[all] qiskit-qrack-provider && pip cache purge

# Install IBM QC connector
RUN pip3 install -U IBMQuantumExperience && pip cache purge

# install IQM connectors and libary
RUN pip3 install qiskit-iqm && pip cache purge

# install cirq and mitiq
RUN pip3 install mitiq[all] && pip cache purge

# install google agent development kit
RUN pip3 install google-adk && pip cache purge

# install pennylane and openfermion dependancies for pyqrack vqe 
RUN pip install pennylane pennylane-qrack openfermion openfermionpyscf

# clone repos
RUN git clone --recursive --depth=1 --recursive https://github.com/unitaryfund/qrack.git
RUN git clone --recursive --depth=1 --recursive https://github.com/unitaryfund/pyqrack.git

# Qrack install & dependancies 
RUN cd /qrack/include && mkdir CL && cd /qrack && mkdir _build && cd _build && cmake -DENABLE_DEVRAND=ON -DFPPOW=5 -DUINTPOW=6 -DQBCAPPOW=6 -DENABLE_COMPLEX_X2=ON .. && make -i -k -j $(grep -c ^processor /proc/cpuinfo) all  && make install

# HF and Open-interpreter dependancies
RUN export DEBIAN_FRONTEND=noninteractive && apt update && apt install -y python3-pip npm ipython3 python-is-python3 ffmpeg python3-venv libgl1 libglib2.0-0 && apt clean all
RUN pip3 install huggingface_hub[hf_transfer] && pip cache purge

# install open-interpreter
RUN pip3 install --upgrade open-interpreter && pip cache purge

# fetch localai
# RUN curl https://localai.io/install.sh | sh && apt clean all

# fetch ollama
RUN curl -fsSL https://ollama.com/install.sh | sh

# install open-interpreter web UI
RUN git clone --depth=1 https://github.com/blazzbyte/OpenInterpreterUI.git
RUN cd OpenInterpreterUI && pip3 install -r requirements.txt && pip cache purge
# matplotlib fix
RUN apt remove -y python3-matplotlib

COPY runfiles/run-agent /root/run-agent
RUN chmod 744 /root/run-agent

EXPOSE 6080 8888
ENTRYPOINT /root/run-agent
