FROM twobombs/thereminq-tensors

RUN apt update && apt install cmake nodejs npm libssl-dev gnome-calculator && apt clean all
RUN git clone https://github.com/iqm-finland/KQCircuits.git & git clone https://github.com/iqm-finland/qiskit-on-iqm.git

# Install pyqrack + couplings, runtime requirements
RUN pip3 install --upgrade qiskit-metal pyqrack

# Install IBM QC connector
RUN pip3 install -U IBMQuantumExperience
# Install Qiskit
RUN pip3 install qiskit[visualization] qiskit-qrack-provider
# install IQM connectors and libary
RUN pip3 install qiskit-iqm 

COPY runfiles/run /root/run
EXPOSE 6080
ENTRYPOINT /root/run
