FROM twobombs/thereminq-tensors

RUN pip3 install jupytext ipython tensorboard tensorflow tensorflow_gnn tensorflow-datasets jupyter traitlets nbconvert matplotlib jupyter_http_over_ws jupyterlab notebook jupyter-book && pip cache purge

# tensorflow-quantum
# RUN git clone --depth=1 https://github.com/tensorflow/quantum.git && cd quantum && pip install -r requirements.txt && pip cache purge

# mdopt install
# RUN pip3 install mdopt && pip cache purge
RUN cd notebooks/uf/mdopt && pip3 install --ignore-installed -r requirements.txt && pip cache purge

# convert md / py / ipynb files
RUN cd notebooks/qrack/pyqrack-jupyter && jupyter nbconvert --to script *.ipynb
RUN cd /notebooks/google/Cirq/docs/simulate && jupyter nbconvert --to script *.ipynb

# convert some of the py files to ipynb for convenience
RUN cd /notebooks/uf/qrack/pyqrack-examples && jupytext --to notebook *.py
RUN cd /notebooks/uf/qrack/simulator-benchmarks && jupytext --to notebook *.py

RUN cd /notebooks/uf/qrack/qiskit-qrack-provider/test/benchmark && jupytext --to notebook *.py
RUN cd /notebooks/uf/qrack/qiskit-qrack-provider/qiskit/providers/qrack && jupytext --to notebook *.py

RUN cd notebooks && mkdir tensorboard-projector && cd tensorboard-projector && wget https://storage.googleapis.com/tensorflow_docs/tensorboard/docs/tensorboard_projector_plugin.ipynb

EXPOSE 6080
ENTRYPOINT /root/run-boards
