FROM twobombs/deploy-nvidia-docker:minimum

# Install pyqrack en reqs.
RUN apt-get update && apt-get install -y python3-pip && apt clean all 
RUN pip install --break-system-packages pyqrack pyzx ipyparallel mistune pennylane && pip cache purge

# benchmarks
RUN git clone --depth=1 https://github.com/vm6502q/pyqrack-jupyter.git

# Install SimulaQron 
# RUN pip3 install simulaqron
# RUN simulaqron set backend pyqrack

# Install IBM QC connector
RUN pip3 install --break-system-packages -U IBMQuantumExperience && pip cache purge

# Install Qiskit
RUN pip3 install --break-system-packages qiskit[visualization] && pip cache purge
RUN pip3 install  --break-system-packages qiskit-qrack-provider && pip cache purge

# Install qc-client WebUI
RUN apt install -y npm && npm install -g qps-client & apt clean all

EXPOSE 6006 8888
COPY runfiles/run-minimum-tensor /root/run-minimum-tensor
ENTRYPOINT /root/run-minimum-tensor
