FROM twobombs/thereminq-tensors

# install apt packages because 
RUN apt update && apt install -y pybind11-dev cmake nodejs npm libssl-dev xxd libgmp3-dev && apt clean all

#ipython jupyter install
RUN pip3 install jupytext jupyter ipython && pip cache purge

# convert md / py / ipynb files
RUN cd notebooks/qrack/pyqrack-jupyter && jupyter nbconvert --to script *.ipynb
RUN cd /notebooks/google/Cirq/docs/simulate && jupyter nbconvert --to script *.ipynb

# convert some of the py files to ipynb for convenience
RUN cd /notebooks/qrack/pyqrack-examples && jupytext --to notebook *.py
RUN cd /notebooks/qrack/pyqrack-examples/rcs && jupytext --to notebook *.py
RUN cd /notebooks/qrack/pyqrack-examples/qbdd && jupytext --to notebook *.py

RUN cd /notebooks/qrack/simulator-benchmarks && jupytext --to notebook *.py

RUN cd /notebooks/qrack/qiskit-qrack-provider/test/benchmark && jupytext --to notebook *.py
RUN cd /notebooks/qrack/qiskit-qrack-provider/qiskit/providers/qrack && jupytext --to notebook *.py

# install rsa primes UI & Shors' input requirement. 
RUN add-apt-repository -y ppa:linuxuprising/libpng12 && apt update && apt install libboost-all-dev opencl-headers xxd libpng12-0 libcanberra-gtk-module gtk2-engines-pixbuf libcanberra-gtk3-module && apt clean all
RUN apt update && apt install libgtest-dev gnome-calculator mathomatic-primes mathomatic libssl-dev && apt clean all

RUN git clone --depth=1 https://github.com/twobombs/qrackmin.git && cd qrackmin/deploy-scripts && tar -xf qimcifa64.tar.gz -C /

# 128+ qimcifa with loadbalancer
RUN git clone --depth=1 https://github.com/vm6502q/qimcifa.git && mv qimcifa qimcifa128 && cd /qimcifa128 && cmake -DBIG_INT_BITS=128 . && make
RUN git clone --depth=1 https://github.com/vm6502q/qimcifa.git && mv qimcifa qimcifa512 && cd /qimcifa512 && cmake -DBIG_INT_BITS=512 . && make
RUN git clone --depth=1 https://github.com/vm6502q/qimcifa.git && mv qimcifa qimcifa1024 && cd /qimcifa1024 && cmake -DBIG_INT_BITS=1024 . && make

# 128+ qimcifa with RND dispatcher
RUN git clone --depth=1 https://github.com/vm6502q/qimcifa.git && mv qimcifa qimcifa128rnd && cd /qimcifa128rnd && cmake -DBIG_INT_BITS=128 -DIS_RANDOM=ON . && make
RUN git clone --depth=1 https://github.com/vm6502q/qimcifa.git && mv qimcifa qimcifa512rnd && cd /qimcifa512rnd && cmake -DBIG_INT_BITS=512 -DIS_RANDOM=ON . && make
RUN git clone --depth=1 https://github.com/vm6502q/qimcifa.git && mv qimcifa qimcifa1024rnd && cd /qimcifa1024rnd && cmake -DBIG_INT_BITS=1024 -DIS_RANDOM=ON . && make

# old bigint build
RUN git clone --depth=1 --branch opencl_bigint https://github.com/vm6502q/qimcifa.git && mv qimcifa qimcifa-bigint && cd qimcifa-bigint && cmake . && make

# find a factor pip install
RUN git clone https://github.com/vm6502q/FindAFactor.git && cd FindAFactor && pip3 install . && pip cache purge

# NV's BigINT implementation + reqs
RUN git clone --depth=1 https://github.com/google/googletest.git && cd googletest && cmake . && make && make install 
RUN git clone --depth=1 https://github.com/NVlabs/CGBN.git && cd CGBN && mv /googletest/googletest gtest && make

COPY runfiles/* /root 
COPY runfiles/shors_winloop.sh /pyqrack-jupyter/shors_winloop.sh
COPY runfiles/shors_modulus.sh /pyqrack-jupyter/shors_modulus.sh
RUN cd /root && chmod 755 run* && chmod 755 shors*
#
# make log dir for measured results
RUN mkdir /var/log/shors
#
EXPOSE 6080
ENTRYPOINT /root/run-shors
