FROM twobombs/thereminq-tensors

# python-is-python3
apt install -y python-is-python3 && apt clean all

# add the CrewAI and Autogenstudio Agents
RUN git clone https://github.com/joaomdmoura/crewAI.git
RUN pip3 install crewai[tools] autogenstudio open-interpreter

# fetch ollama
RUN curl -fsSL https://ollama.com/install.sh | sh

# install open-interpreter web UI
RUN git clone --depth=1 https://github.com/blazzbyte/OpenInterpreterUI.git
RUN cd OpenInterpreterUI && pip3 install -r requirements.txt && pip cache purge

COPY runfiles/run /root/run-agent
EXPOSE 6080 8888
ENTRYPOINT /root/run-agent
