FROM twobombs/thereminq-tensors

RUN apt install gfortran && apt clean all
RUN git clone https://github.com/lattice/quda && mkdir qudabuild && cd qudabuild && cmake -DQUDA_GPU_ARCH=sm_30 /quda/ && make -j 2 && make install

EXPOSE 6080
ENTRYPOINT /root/run
