FROM twobombs/thereminq-tensors

# install rsa primes UI & Shors' input requirement. 
RUN add-apt-repository -y ppa:linuxuprising/libpng12 && apt update && apt install libboost-all-dev opencl-headers xxd libpng12-0 libcanberra-gtk-module gtk2-engines-pixbuf libcanberra-gtk3-module && apt clean all
RUN apt update && apt install gnome-calculator mathomatic-primes mathomatic libssl-dev && apt clean all
#
# nerfed rsa prime generators install
# RUN git clone https://github.com/openssh/openssh-portable.git && cd openssh-portable && autoreconf && sed -i 's/#define SSH_RSA_MINIMUM_MODULUS_SIZE.*/#define SSH_RSA_MINIMUM_MODULUS_SIZE   1024/g' sshkey.h && ./configure && make && mkdir /var/empty && make tests && make install
# RUN git clone https://github.com/openssl/openssl.git && cd openssl && ./Configure enable-weak-ssl-ciphers -DOPENSSL_TLS_SECURITY_LEVEL=0 && make && make install
#
# vm6502q/qimcifa has an LGPL license. Report (re)use of code to Dan Strano.
RUN git clone https://github.com/vm6502q/qimcifa.git && cd /qimcifa && cmake . && make
#
RUN mkdir /root/.ssh
#
COPY runfiles/run-shors /root/run-shors
COPY runfiles/shors_winloop.sh /pyqrack-jupyter/shors_winloop.sh
COPY runfiles/shors_modulus.sh /pyqrack-jupyter/shors_modulus.sh
COPY runfiles/shors_modulus.sh /pyqrack-jupyter/shors_modulus.sh
COPY runfiles/shors_qimcifa_loop.sh /root/shors_qimcifa_loop.sh
#
EXPOSE 6080
ENTRYPOINT /root/run-shors
