FROM twobombs/deploy-nvidia-docker:minimum

# Install pyqrack en reqs.
RUN apt-get update && apt-get install -y --break-system-packages python3-pip
RUN pip install --break-system-packages pyqrack pyzx ipyparallel mistune pennylane

# benchmarks
RUN git clone --depth=1 https://github.com/vm6502q/pyqrack-jupyter.git

# Install SimulaQron 
# RUN pip3 install simulaqron
# RUN simulaqron set backend pyqrack

# Install IBM QC connector
RUN pip3 install --break-system-packages -U IBMQuantumExperience

# Install Qiskit
RUN pip3 install --break-system-packages qiskit[visualization]
RUN pip3 install  --break-system-packages qiskit-qrack-provider

# Install qc-client WebUI
RUN apt install -y npm && npm install -g qps-client & apt clean all

EXPOSE 6006 8888
COPY runfiles/run-minimum-tensor /root/run-minimum-tensor
ENTRYPOINT /root/run-minimum-tensor
