FROM twobombs/thereminq-tensors

RUN apt install gfortran && apt clean all
RUN git clone https://github.com/lattice/quda && mkdir qudabuild && cd qudabuild && cmake -DQUDA_GPU_ARCH=3.0 /quda/ && make && make install

EXPOSE 6080
ENTRYPOINT /root/run
