FROM twobombs/thereminq-tensors

RUN apt update && apt install cmake nodejs npm libssl-dev gnome-calculator && apt clean all

# Install pyqrack + couplings, runtime requirements
RUN pip3 install --upgrade qiskit-metal pyqrack

# Install IBM QC connector
RUN pip3 install -U IBMQuantumExperience
# Install Qiskit
RUN pip3 install qiskit[visualization] qiskit-qrack-provider

COPY runfiles/run /root/run
EXPOSE 6080
ENTRYPOINT /root/run
