FROM twobombs/thereminq-tensors:metal

# add the CrewAI 
RUN git clone https://github.com/joaomdmoura/crewAI.git
RUN pip3 install crewai[tools] autogenstudio 

COPY runfiles/run /root/run-metal
EXPOSE 6080 8888
ENTRYPOINT /root/run-metal
