FROM twobombs/thereminq-tensors

RUN pip3 install jupytext ipython tensorboard cirq tensorflow tensorflow_gnn tensorflow-datasets jupyter traitlets nbconvert matplotlib jupyter_http_over_ws jupyterlab notebook jupyter-book && pip cache purge

# tensorflow-quantum
# RUN git clone --depth=1 https://github.com/tensorflow/quantum.git && cd quantum && pip install -r requirements.txt && pip cache purge

# install dask
# RUN apt install -y python3-pip && apt clean all && pip3 install dask-cuda cupy joblib matplotlib && pip3 cache purge

# mdopt install
# RUN pip3 install mdopt && pip cache purge
# RUN cd notebooks/uf/mdopt && pip3 install --ignore-installed -r requirements.txt && pip cache purge

# install pennylane, openfermion and other dependancies for pyqrack vqe benchmark scripts
RUN apt install -y libopenblas-dev && apt clean all
RUN pip install --prefer-binary --upgrade pyscf && pip cache purge
RUN pip install --prefer-binary --upgrade pennylane pennylane-qrack openfermion openfermionpyscf pennylane-qchem pennylane-cirq cirq matplotlib autograd && pip cache purge

# convert md / py / ipynb files
RUN cd notebooks/qrack/pyqrack-jupyter && jupyter nbconvert --to script *.ipynb
RUN cd /notebooks/google/Cirq/docs/simulate && jupyter nbconvert --to script *.ipynb

# convert some of the py files to ipynb for convenience
RUN cd /notebooks/qrack/pyqrack-examples && jupytext --to notebook *.py
RUN cd /notebooks/qrack/pyqrack-examples/rcs && jupytext --to notebook *.py
RUN cd /notebooks/qrack/pyqrack-examples/qbdd && jupytext --to notebook *.py
RUN cd /notebooks/qrack/simulator-benchmarks && jupytext --to notebook *.py
RUN cd /notebooks/qrack/qiskit-qrack-provider/test/benchmark && jupytext --to notebook *.py
RUN cd /notebooks/qrack/qiskit-qrack-provider/qiskit/providers/qrack && jupytext --to notebook *.py
RUN cd /notebooks/thereminq-tensors/runfiles && jupytext --to notebook *.py

# legacy: place tensorboard projector project 
RUN cd notebooks && mkdir tensorboard-projector && cd tensorboard-projector && wget https://storage.googleapis.com/tensorflow_docs/tensorboard/docs/tensorboard_projector_plugin.ipynb

EXPOSE 6080
ENTRYPOINT /root/run-boards
