FROM twobombs/thereminq-tensors

# python-is-python3
RUN apt install -y python-is-python3 && apt clean all

# add CrewAI agents
RUN git clone https://github.com/joaomdmoura/crewAI.git
RUN pip3 install crewai[tools]

# visualisation
RUN git clone --depth=1 https://github.com/AbubakrChan/crewai-business-product-launch.git
RUN cd crewai-business-product-launch && pip install -r requirements.txt && pip cache purge
# run with streamlit run main.py

# RUN git clone --depth=1 https://github.com/Eng-Elias/CrewAI-Visualizer
# RUN cd CrewAI-Visualizer && chmod 744 setup_linux_mac.sh && ./setup_linux_mac.sh

# agent will require quantum dependancies

# install runtime requirements
# to speed up the agent process
RUN pip3 install --upgrade pip
RUN pip3 install pyqrack && pip cache purge

# Install Qiskit libaries
RUN pip3 install qiskit[all] qiskit-qrack-provider && pip cache purge

# Install IBM QC connector
RUN pip3 install -U IBMQuantumExperience && pip cache purge

# install IQM connectors and libary
RUN pip3 install qiskit-iqm && pip cache purge

# install cirq and mitiq
RUN pip3 install cirq[all] mitiq[all] && pip cache purge

# HF and Open-interpreter dependancies
RUN export DEBIAN_FRONTEND=noninteractive && apt install -y python3-pip npm ipython3 python-is-python3 ffmpeg python3-venv libgl1 libglib2.0-0 && apt clean
RUN pip3 install huggingface_hub[hf_transfer] && pip cache purge

# install open-interpreter
RUN pip3 install open-interpreter && pip cache purge

# fetch ollama
RUN curl -fsSL https://ollama.com/install.sh | sh

# install open-interpreter web UI
RUN git clone --depth=1 https://github.com/blazzbyte/OpenInterpreterUI.git
RUN cd OpenInterpreterUI && pip3 install -r requirements.txt && pip cache purge
# matplotlib fix
RUN apt remove -y python3-matplotlib

COPY runfiles/run-agent /root/run-agent
RUN chmod 744 /root/run-agent

EXPOSE 6080 8888
ENTRYPOINT /root/run-agent
