FROM twobombs/cudacluster:2204dev

# install dependancies
RUN apt update &&  yes | apt install -y msttcorefonts -qq & sleep 160 && echo && sleep 160
RUN pip3 install --ignore-installed jupyter jupytext ipython tensorboard tensorflow tensorflow_gnn tensorflow-datasets && pip cache purge
RUN pip3 install --ignore-installed traitlets nbconvert matplotlib jupyter_http_over_ws jupyterlab notebook jupyter-book && pip cache purge
RUN pip3 install --ignore-installed union cirq qiskit ply mitiq && pip cache purge

# prep notebooks for repos and convert files to notebooks
RUN mkdir notebooks && cd notebooks && git clone https://github.com/unitaryfund/mitiq.git 
RUN cd /notebooks/mitiq/docs/source/examples/ && jupytext --to notebook *.md

COPY runfiles/run-boards /root/run-boards
RUN chmod 755 /root/run*

EXPOSE 6080
ENTRYPOINT /root/run-boards
