FROM twobombs/deploy-nvidia-docker:minimum

# Install pyqrack en reqs.
RUN apt-get update && apt-get install -y python3-pip python3-numpy
RUN pip install pyqrack
RUN pip install pyzx
RUN pip install cirq
# RUN pip install mitiq - numpy python>3.10 wheel probs
RUN pip install ipyparallel
RUN pip install mistune
RUN pip install pennylane
RUN pip install pennylane-qrack
# RUN pip install qutechopenql - similar fail

# benchmarks
RUN git clone https://github.com/vm6502q/pyqrack-jupyter.git

# Install SimulaQron 
# RUN pip3 install simulaqron
# RUN simulaqron set backend pyqrack

# Install IBM QC connector
RUN pip3 install -U IBMQuantumExperience

# Install Qiskit
RUN pip3 install qiskit[visualization]
RUN pip3 install qiskit-qrack-provider

# Install qc-client WebUI
RUN apt install -y npm && npm install -g qps-client & apt clean all

EXPOSE 6006 8888
COPY runfiles/run-minimum-tensor /root/run-minimum-tensor
ENTRYPOINT /root/run-minimum-tensor
